### PR TITLE
fixing deprecation warning

### PR DESCRIPTION
**Pull request by georgiablanco**
fixing deprecation warning

image

### CODE REVIEW

**Comment by lianghongzhuo** [comment]
```
Using load_yaml() directly is deprecated. Use xacro.load_yaml() instead.
Using load_yaml() directly is deprecated. Use xacro.load_yaml() instead.
Using load_yaml() directly is deprecated. Use xacro.load_yaml() instead.
Using load_yaml() directly is deprecated. Use xacro.load_yaml() instead.
redefining global symbol: pi
```
Easier  for issuse search :)

**Comment by lianghongzhuo** [comment]
@fmauch please merge

**Comment by fmauch** [comment]
Sorry for not answering this for so long. As I'd like to merge my fork upstream, I'd like to keep changes here to a minimum. Things are looking as if there will be some updates soon, though...

**Comment by fmauch** [comment]
Closing in favor of https://github.com/ros-industrial/universal_robot/pull/602

**Pull request closed without merging**
